repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        exclude: ^(tests|migrations)/
-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        exclude: ^(tests|migrations)/

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0
    hooks:
    -   id: autopep8
        exclude: ^(tests|migrations)/
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        exclude: ^(tests|migrations)/
-   repo: https://github.com/pycqa/pylint
    rev: v2.14.5
    hooks:
    -   id: pylint
        exclude: ^(tests|migrations)/
        args:
        - --max-line-length=100
        - --ignore-imports=yes
        - -d duplicate-code
        - --errors-only
        - --disable=F0401, E0213
