site_name: HotelAPI

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - Hotel Docs: index.md
  - 'About':
    - General Info: general-info.md
    - Database design: HotelAPI_db.md
  - 'User Guide':
    - Installation: installation.md
    - Routers overview: overview.md
    - How-To Guides: how-to-guides.md
  - 'Tests coverage report':
    - Coverage report: coverage.md
