site_name: HotelAPI

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - Installation: installation.md
  - Hotel Docs: index.md
  - General Info: general-info.md
  - Database design: HotelAPI_db.md
  # - How-To Guides: how-to-guides.md  
  # - explanation.md
